name: CI/CD swapi

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-code:
    name: Lint and Format Python Code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black in check mode
        run: |
          black --check .
  docker:
    name: Build container and push to Docker Hub
    runs-on: ubuntu-latest
    needs: lint-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aruizdlt/swapi
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
